version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - restore_cache:
          key: 'rosnovsky-us-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: 'rosnovsky-us-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run:
          name: Prettier
          command: ./node_modules/.bin/prettier --print-width=100 --trailing-comma=es5 --single-quote --list-different './src/**/*.{js,jsx,ts,tsx}'
      - run: yarn lint

workflows:
  version: 2
  tests:
    jobs:
      - build