version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - checkout
      - restore_cache:
          key: 'rosnovsky-us-v1-{{ checksum "yarn.lock" }}'
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: 'rosnovsky-us-v1-{{ checksum "yarn.lock" }}'
          paths:
            - ./node_modules
      - run:
          name: Prettier
          command: ./node_modules/.bin/prettier --semi=true --single-quote=true --trailing-comma=es5 --check './src/**/*.{js,jsx,ts,tsx}'

workflows:
  version: 2
  tests:
    jobs:
      - build
